import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/layouts/header";
import Footer from "../components/layouts/footer";
import { AnimateSharedLayout } from "framer-motion";
import { useState } from "react";
import Body from "../components/layouts/body";
import Modal from "../components/common/modal";
import Content from "../components/common/Modal/modal-content";
import { ModalContext } from "../context/modalContext";

const Home: NextPage = () => {
  const [modal, setModal] = useState(false);
  const [link, setLink] = useState("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ModalContext.Provider value={{ modal, setModal, link, setLink }}>
          <Modal {...{ modal, setModal }} />
          <Content {...{ modal, setModal }}>
            <>
              <Header />
              <Body />
              <Footer />
            </>
          </Content>
        </ModalContext.Provider>
      </main>
    </>
  );
};

export default Home;
